import { forwardRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useBox } from '@react-three/cannon'

useGLTF.preload('/cyberpunkcar.glb')

// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Model via KrStolorz on Sketchfab, CC-BY-4.0
// https://sketchfab.com/3d-models/low-poly-volkswagen-beetle-f680ad7e98e445eaafed1a70f2c53911
const Cyberpunkcar = forwardRef(({ args = [1.7, 1, 4], mass = 500, ...props }, ref) => {
  const { nodes, materials } = useGLTF('/cyberpunkcar.glb')
  const [, api] = useBox(() => ({ mass, args, allowSleep: false, onCollide: (e) => console.log('bonk', e.body.userData), ...props }), ref)
  return (
    <mesh ref={ref} api={api}>
    <group>
      <group rotation={[-Math.PI / 2, 0, 9.5]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, -0.53, 0.48]} rotation={[0, 0, -Math.PI / 2]} scale={0.61}>
            <mesh geometry={nodes.Object_4.geometry} material={materials.KABEL_KECIL} />
          </group>
          <mesh geometry={nodes.Object_6.geometry} material={materials.BASE_2} />
          <mesh geometry={nodes.Object_8.geometry} material={materials.BASE_2} />
          <mesh geometry={nodes.Object_10.geometry} material={materials.BASE_2} />
          <mesh geometry={nodes.Object_12.geometry} material={materials.BASE_2} />
          <mesh geometry={nodes.Object_14.geometry} material={materials.BASE_2} />
          <mesh geometry={nodes.Object_16.geometry} material={materials.BASE_2} />
          <mesh geometry={nodes.Object_18.geometry} material={materials.METAL} />
          <mesh geometry={nodes.Object_20.geometry} material={materials.BASE_2} />
          <mesh geometry={nodes.Object_22.geometry} material={materials.BASE_2} />
          <mesh geometry={nodes.Object_24.geometry} material={materials.BASE_2} />
          <mesh geometry={nodes.Object_26.geometry} material={materials.LAMPU_BELAKANG} />
          <mesh geometry={nodes.Object_28.geometry} material={materials.BASE_2} />
          <mesh geometry={nodes.Object_30.geometry} material={materials.BASE_2} />
          <mesh geometry={nodes.Object_32.geometry} material={materials.BASE_3} />
          <mesh geometry={nodes.Object_34.geometry} material={materials.BASE} />
          <mesh geometry={nodes.Object_36.geometry} material={materials.BASE} />
          <mesh geometry={nodes.Object_38.geometry} material={materials.BASE} />
          <mesh geometry={nodes.Object_40.geometry} material={materials.BASE} />
          <mesh geometry={nodes.Object_42.geometry} material={materials.BASE} />
          <group position={[0, 0.01, 0]}>
            <mesh geometry={nodes.Object_44.geometry} material={materials.BASE} />
          </group>
          <mesh geometry={nodes.Object_46.geometry} material={materials.BASE} />
          <group position={[0, -0.02, 0]}>
            <mesh geometry={nodes.Object_48.geometry} material={materials.METAL} />
          </group>
          <mesh geometry={nodes.Object_50.geometry} material={materials.BASE_2} />
          <mesh geometry={nodes.Object_52.geometry} material={materials.BASE_2} />
          <mesh geometry={nodes.Object_53.geometry} material={materials.BASE_4} />
          <mesh geometry={nodes.Object_55.geometry} material={materials.METAL} />
          <mesh geometry={nodes.Object_56.geometry} material={materials.BASE_4} />
          <mesh geometry={nodes.Object_58.geometry} material={materials.BASE_2} />
          <mesh geometry={nodes.Object_59.geometry} material={materials.BASE_4} />
          <mesh geometry={nodes.Object_61.geometry} material={materials.BASE_2} />
          <mesh geometry={nodes.Object_63.geometry} material={materials.BASE_2} />
          <mesh geometry={nodes.Object_64.geometry} material={materials.KACA} />
          <mesh geometry={nodes.Object_66.geometry} material={materials.BASE_2} />
          <mesh geometry={nodes.Object_67.geometry} material={materials.KACA} />
          <mesh geometry={nodes.Object_69.geometry} material={materials.BASE_2} />
          <mesh geometry={nodes.Object_70.geometry} material={materials.KACA} />
          <mesh geometry={nodes.Object_72.geometry} material={materials.KACA} />
          <mesh geometry={nodes.Object_74.geometry} material={materials.BASE_2} />
          <mesh geometry={nodes.Object_75.geometry} material={materials.LAMPU_ATAS} />
          <mesh geometry={nodes.Object_77.geometry} material={materials.BASE_2} />
          <mesh geometry={nodes.Object_78.geometry} material={materials.LAMPU_ATAS} />
          <mesh geometry={nodes.Object_80.geometry} material={materials.BASE_2} />
          <mesh geometry={nodes.Object_81.geometry} material={materials.LAMPU_ATAS} />
          <mesh geometry={nodes.Object_83.geometry} material={materials.BASE_2} />
          <mesh geometry={nodes.Object_85.geometry} material={materials.BASE_2} />
          <mesh geometry={nodes.Object_87.geometry} material={materials.BASE_2} />
          <mesh geometry={nodes.Object_89.geometry} material={materials.BASE_2} />
          <mesh geometry={nodes.Object_91.geometry} material={materials.BASE_2} />
          <mesh geometry={nodes.Object_93.geometry} material={materials.BASE_2} />
          <mesh geometry={nodes.Object_95.geometry} material={materials.METAL} />
          <mesh geometry={nodes.Object_97.geometry} material={materials.BASE_2} />
          <mesh geometry={nodes.Object_99.geometry} material={materials['LAMPU_BELAKANG.001']} />
          <mesh geometry={nodes.Object_101.geometry} material={materials.METAL} />
          <mesh geometry={nodes.Object_103.geometry} material={materials.BASE_2} />
          <mesh geometry={nodes.Object_104.geometry} material={materials.LAMPU_DEPAN} />
          <mesh geometry={nodes.Object_106.geometry} material={materials.BASE_2} />
          <mesh geometry={nodes.Object_107.geometry} material={materials.LAMPU_DEPAN} />
          <mesh geometry={nodes.Object_109.geometry} material={materials.BASE_3} />
          <mesh geometry={nodes.Object_111.geometry} material={materials.BASE_2} />
          <mesh geometry={nodes.Object_113.geometry} material={materials.BASE_2} />
          <mesh geometry={nodes.Object_115.geometry} material={materials.METAL} />
          <mesh geometry={nodes.Object_117.geometry} material={materials.METAL} />
          <mesh geometry={nodes.Object_119.geometry} material={materials.BASE} />
          <group position={[0, -0.02, 0.04]}>
            <mesh geometry={nodes.Object_121.geometry} material={materials.LAMPU_BELAKANG} />
          </group>
          <mesh geometry={nodes.Object_123.geometry} material={materials.BASE} />
          <mesh geometry={nodes.Object_124.geometry} material={materials.METAL} />
          <mesh geometry={nodes.Object_125.geometry} material={materials.LAMPU_BELAKANG} />
          <mesh geometry={nodes.Object_127.geometry} material={materials.METAL} />
          <mesh geometry={nodes.Object_129.geometry} material={materials.BASE} />
          <group position={[0, 0, -0.33]}>
            <mesh geometry={nodes.Object_131.geometry} material={materials.METAL} />
          </group>
          <mesh geometry={nodes.Object_133.geometry} material={materials.METAL} />
          <mesh geometry={nodes.Object_135.geometry} material={materials.METAL} />
          <mesh geometry={nodes.Object_137.geometry} material={materials.BASE} />
          <mesh geometry={nodes.Object_138.geometry} material={materials.BASE} />
          <mesh geometry={nodes.Object_139.geometry} material={materials.BASE} />
          <mesh geometry={nodes.Object_140.geometry} material={materials.BASE} />
          <mesh geometry={nodes.Object_141.geometry} material={materials.BASE} />
          <mesh geometry={nodes.Object_142.geometry} material={materials.BASE} />
          <mesh geometry={nodes.Object_143.geometry} material={materials.BASE} />
          <mesh geometry={nodes.Object_144.geometry} material={materials.BASE} />
          <mesh geometry={nodes.Object_145.geometry} material={materials.LAMPU_BELAKANG} />
          <mesh geometry={nodes.Object_146.geometry} material={materials.LAMPU_BELAKANG} />
          <mesh geometry={nodes.Object_148.geometry} material={materials.BASE_2} />
          <mesh geometry={nodes.Object_150.geometry} material={materials.METAL} />
          <mesh geometry={nodes.Object_152.geometry} material={materials.METAL} />
          <mesh geometry={nodes.Object_154.geometry} material={materials.BASE_2} />
          <mesh geometry={nodes.Object_156.geometry} material={materials.BASE_2} />
          <mesh geometry={nodes.Object_158.geometry} material={materials.METAL} />
          <mesh geometry={nodes.Object_160.geometry} material={materials.BASE_2} />
          <mesh geometry={nodes.Object_161.geometry} material={materials.BASE_2} />
          <mesh geometry={nodes.Object_162.geometry} material={materials.BASE_2} />
          <mesh geometry={nodes.Object_163.geometry} material={materials.BASE_2} />
          <mesh geometry={nodes.Object_164.geometry} material={materials.BASE_2} />
          <mesh geometry={nodes.Object_165.geometry} material={materials.BASE_2} />
          <mesh geometry={nodes.Object_166.geometry} material={materials.BASE_2} />
          <mesh geometry={nodes.Object_167.geometry} material={materials.BASE_2} />
          <mesh geometry={nodes.Object_168.geometry} material={materials.BASE_2} />
          <mesh geometry={nodes.Object_169.geometry} material={materials.BASE_2} />
          <mesh geometry={nodes.Object_171.geometry} material={materials.METAL} />
        </group>
      </group>
    </group>
    </mesh>
  )
})

export default Cyberpunkcar
